# Generated by Django 4.2.1 on 2023-06-18 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='author_email',
        ),
    ]
