# Generated by Django 4.2.1 on 2023-05-10 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0003_alter_question_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answered',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
