# Generated by Django 4.2.1 on 2023-05-10 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0005_answer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
