# Generated by Django 4.2.1 on 2023-06-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_room_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='size',
            field=models.PositiveIntegerField(),
        ),
    ]
