# Generated by Django 4.2.1 on 2023-06-18 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_reservation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
