# Generated by Django 4.2.1 on 2023-06-07 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_room_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='availRoom',
            field=models.PositiveIntegerField(default=3),
            preserve_default=False,
        ),
    ]
