# Generated by Django 4.2.1 on 2023-06-18 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_reservation_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='phone_number',
        ),
    ]
